"""initial

Revision ID: be288a524be3
Revises:
Create Date: 2025-04-09 10:34:09.369498
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be288a524be3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("customer_id", sa.Integer(), nullable=False),  # Renamed 'id' to 'customer_id'
        sa.Column("customer_name", sa.String(), nullable=False),
        sa.Column("payment", sa.String(), nullable=True),
        sa.Column("character_class", sa.String(), nullable=False),  # Added character_class
        sa.Column("level", sa.Integer(), nullable=False),  # Added level
        sa.PrimaryKeyConstraint("customer_id"),  # Set the primary key on customer_id
    )
    op.create_table(
        "global_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gold", sa.Integer(), nullable=False),
        sa.Column("red_ml", sa.Integer(), nullable=False),
        sa.Column("green_ml", sa.Integer(), nullable=False),
        sa.Column("blue_ml", sa.Integer(), nullable=False),
        sa.Column("red_potions", sa.Integer(), nullable=False),
        sa.Column("green_potions", sa.Integer(), nullable=False),
        sa.Column("blue_potions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("item_sku", sa.String(), nullable=False),  # Changed to item_sku
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()),  # Added timestamp column
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.customer_id"],  # Updated foreign key constraint to reference customer_id
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_items")
    op.drop_table("global_inventory")
    op.drop_table("carts")
    # ### end Alembic commands ###
